# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# This is a template for Docker image build. NOT FOR DEPLOY

trigger:
  tags:
    include:
    - refs/tags/springapp-*

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageAndPublishArtifactsAndDocker
    displayName: Maven Package and Publish Artifacts and Docker
    pool:
      vmImage: $(vmImageName)
    
    steps:
    # - task: MavenAuthenticate@0
    #   inputs:
    #     artifactsFeeds: 'VictorKLee'

    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: '-DskipTests package'
        # package without testing until DB is readily connected

    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: $(Build.ArtifactStagingDirectory)

    - upload: $(Build.ArtifactStagingDirectory)
      artifact: drop

    - task: Docker@2
      displayName: Build an image
      inputs:
        buildContext: $(Build.ArtifactStagingDirectory)
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)